---
# deploy_rancher_via_helm/tasks/install_packages.yml

- name: "Install packages required by Ansible's helm module"
  ansible.builtin.package:
    name: "{{ required_packages }}"
    state: 'present'
